### ISSUE TITLE
Manage Employees - View Employee Details

### ISSUE THREAD

**Issue by ATAshmore** [aseghehey/vehicle-tracking-system#13]
Ideally shouldn't say "No Employee". Maybe we make something print "going back" when you hit q for every page. Minor issue rn.
![image](https://user-images.githubusercontent.com/71903077/229264368-03f145cc-e01f-4fe8-9770-6296a2be4468.png)

**Comment by aseghehey** [comment]
![Image](https://user-images.githubusercontent.com/98903704/229879699-653dabac-1add-4895-a304-cb838f01989c.png)
