### ISSUE TITLE
Customer Order - View Order Details - show employee details (name)

### ISSUE THREAD

**Issue by ATAshmore** [aseghehey/vehicle-tracking-system#15]
Probably should show the employee who was logged in when order was made. first name, last name.
![image](https://user-images.githubusercontent.com/71903077/229265641-1c3940af-4c04-41ce-b2f9-7a74699989b5.png)

**Comment by aseghehey** [comment]
![Image](https://user-images.githubusercontent.com/98903704/229884262-a872ff8e-4e1f-4122-9143-ba269a8e453f.png)



![Image](https://user-images.githubusercontent.com/98903704/229886056-b61f87a8-1525-4cf2-beb1-ca14fb8258b4.png)
