### ISSUE TITLE
Search - Implement view car details

### ISSUE THREAD

**Issue by ATAshmore** [aseghehey/vehicle-tracking-system#18]
Implement option to view car details of selected car.
![image](https://user-images.githubusercontent.com/71903077/229265990-aab2d327-6818-403b-8147-043548924fa2.png)

**Comment by aseghehey** [comment]
![Image](https://user-images.githubusercontent.com/98903704/229887071-b450f2a5-54cb-44d6-af13-09d0bf07ab95.png)



![Image](https://user-images.githubusercontent.com/98903704/229887511-f4d7472c-6ee4-4e34-87d5-fb1be9515162.png)
