### ISSUE TITLE
Search - Remove Car - removing ordered car

### ISSUE THREAD

**Issue by ATAshmore** [aseghehey/vehicle-tracking-system#19]
Should we add validation here? "Are you sure you want to delete car? This is ordered." [y/n]. if y deletus.
![image](https://user-images.githubusercontent.com/71903077/229266096-5d0a1853-9279-4c57-89be-6a2293e4ea3c.png)

**Comment by aseghehey** [comment]
![Image](https://user-images.githubusercontent.com/98903704/229889093-cd6f4f6a-c5c4-44ee-b9e2-ecc42df2a269.png)
