### ISSUE TITLE
Customer Order - Add Order - Existing Customer - all customers deleted scenario

### ISSUE THREAD

**Issue by ATAshmore** [aseghehey/vehicle-tracking-system#21]
I went and deleted all customers for situation where there are no customers yet in the system. Odd scenario for our "get it donee" purposes, but I'll leave this as a request if eventually someone wants to implement.

![image](https://user-images.githubusercontent.com/71903077/229266773-70f2b3c7-fb74-4e7d-a9fd-cae502168598.png)

**Comment by aseghehey** [comment]
fixed
