### ISSUE TITLE
Implement - Manually change ordered car to delivered.

### ISSUE THREAD

**Issue by ATAshmore** [aseghehey/vehicle-tracking-system#24]
Should implement in customer orders menu, view order details or in menu of customer orders as an option 4.
![image](https://user-images.githubusercontent.com/71903077/229267518-68382b5f-f5b3-47aa-84d1-55b5694754d0.png)
either here as option 4. select index to change status to delivered.
or 
![image](https://user-images.githubusercontent.com/71903077/229267536-62ab0ee0-f24b-470c-841d-b46612964d92.png)
change delivery status or press q to exit.

**Comment by aseghehey** [comment]
![Image](https://user-images.githubusercontent.com/98903704/229904812-bc0634f3-2bb2-4a4c-9fd7-642f413ecba8.png)
