### ISSUE TITLE
Grant admin privelege

### ISSUE THREAD

**Issue by ATAshmore** [aseghehey/vehicle-tracking-system#25]
We can make new employees but no way to grant admin privilege. Good to have to be thorough. 

If you decide to add, put it in through MANAGE EMPLOYEES as a new option or go through the view employee details and CHANGE PRIVELEGE. Will also need to edit the add employee function so you can create them as admin status when they are made.

**Comment by aseghehey** [comment]
![Image](https://user-images.githubusercontent.com/98903704/229892058-3046962a-06c6-4c3d-961c-68bb29d291f8.png)

One possible issue with this is that "Manage Employees" rn only displays a list of employees. So if you add an Admin, you will not see them in the list. They are added anyways, but the user will not see them unless we decide to display admins as well.
