### ISSUE TITLE
Manage Customers - edit customer details

### ISSUE THREAD

**Issue by ATAshmore** [aseghehey/vehicle-tracking-system#30]
We should be able to update customer details. It makes sense to add since we'll need to update credit card and shit if that changes. However, prioritize the other fixes to get code working. I'll just remove from the Documentation if so.

**Comment by aseghehey** [comment]
![Image](https://user-images.githubusercontent.com/98903704/230663265-45a435ce-a736-4e6b-8cb7-b34f34223587.png)
