### ISSUE TITLE
file path problem

### ISSUE THREAD

**Issue by ATAshmore** [aseghehey/vehicle-tracking-system#31]
This file path wont work for everyone.
![image](https://user-images.githubusercontent.com/71903077/230552523-1a70ece0-de73-4607-85c2-b21962a0c42f.png)
![image](https://user-images.githubusercontent.com/71903077/230552558-f5c32e89-ba22-4178-adba-0e0f01036594.png)

**Comment by aseghehey** [comment]
yes it works with backslashes for you because you're using windows

i have to figure out why the relative path stopped working, but for now we have to use our local full paths to the json
