### ISSUE TITLE
Search - modify details - change warranty

### ISSUE THREAD

**Issue by ATAshmore** [aseghehey/vehicle-tracking-system#32]
Changing warranty only adds changes and doesn't rewrite. I added warranty 'none' expecting to rewrite all of them but just adds. I think this is fine and I'll just make it in documentation that we can modify warranty by adding to it but not removing the existing warranties. Im fine with this if you prefer it this way(the way it is currently implemented). I would prefer you keep it this way honestly to save time, but i'm just letting you know alternative.
![image](https://user-images.githubusercontent.com/71903077/230557547-1d6f1a1a-859f-49a7-8601-0ba011af744d.png)

**Comment by aseghehey** [comment]
yes my idea is that a car can have as many plans warranty plans as we offer and so i made it an array but i can change it to a string if youd like

or i can give the option to remove from the warranty list
