### ISSUE TITLE
Changing Admin Status?

### ISSUE THREAD

**Issue by ATAshmore** [aseghehey/vehicle-tracking-system#41]
Posting this for now, don't know if its for sure an issue. I previously used this account as an admin and now its changed to general employee. I'm assuming you got rid of the alternating admin and employee thing and just rewrote it. I'll use a different account but this is here to make sure something weird didn't happen.
![image](https://user-images.githubusercontent.com/71903077/230686108-f8643047-a201-4ce7-b455-f99cac707fab.png)

**Comment by aseghehey** [comment]
yes the alternating roles were just for testing purposes
