### ISSUE TITLE
Program dies - Implement check if Employee sold car before deleteing. if they did sell car, cannot delete them from system

### ISSUE THREAD

**Issue by ATAshmore** [aseghehey/vehicle-tracking-system#43]
1. login as user test, test
2.inventory
3. make customer order
4. choose index 1
5. proceed
6. newcustomer
7. successful add and order
8. exit search
9. view orders
10. exit order menu
11. log out
12. death

![image](https://user-images.githubusercontent.com/71903077/230699795-ac7e70b4-01e6-485a-9dd0-a92ed0ea9509.png)

tried launching again
![image](https://user-images.githubusercontent.com/71903077/230700080-39691bb3-cc0d-4774-9788-18147ee27145.png)

so previous to the steps i did earlier i was testing removing employees and logging out but not shutting down the system. so there might be an issue with deleting employees. I think the issue is something to deal with reading the customer order after relaunching and the employee data is no longer there. I**n documentation i was talking about this and how we just make a check to see if the employee has made any sales. if they made any car sales you cannot delete their account.** if this is the issue then i recommend doing that. 

i'll post this and keep testing to see if this is the problem.

**Comment by aseghehey** [comment]
fixed by deleting the orders made by them when they are deleted
