### ISSUE TITLE
Car Sales - formatting 

### ISSUE THREAD

**Issue by ATAshmore** [aseghehey/vehicle-tracking-system#65]
option view sale details needs to be blue and below the "What would you like to do?"
![image](https://user-images.githubusercontent.com/71903077/232328229-a2225ce0-c2bf-41b5-af48-597cd2ec9ee4.png)

**Comment by aseghehey** [comment]
<img width="302" alt="image" src="https://user-images.githubusercontent.com/98903704/232336656-21470c88-2b48-4f16-88ec-4a718f4f437f.png">

**Comment by aseghehey** [comment]
![image](https://user-images.githubusercontent.com/98903704/232495644-1926393d-07b3-481b-82b0-bdd1bb8683e6.png)
