### ISSUE TITLE
Customer Order Menu - should not show delivered cars

### ISSUE THREAD

**Issue by ATAshmore** [aseghehey/vehicle-tracking-system#66]
Do not show delivered cars in Car Orders Menu
![image](https://user-images.githubusercontent.com/71903077/232328453-6d520cc3-04ad-4fef-b5ac-cfc7ad099265.png)
The orders in the image above are from Car Sales. They have status of delivered. This works fine, however, they still show up in Customer Orders menu.
![image](https://user-images.githubusercontent.com/71903077/232328498-fc53c799-4eec-45a3-84ce-c80df551fb4d.png)
![image](https://user-images.githubusercontent.com/71903077/232328514-34912f18-3e63-4529-959c-42017f43c7ca.png)

**Comment by aseghehey** [comment]
i agree but we're tight on time, and doing this now would require to change quite a few other things
